config:
  port: 8081
  grpc_service_name: YourService
  grpc_service_address: 127.0.0.1:50051
  grpc_common_message: CommonValues
  thrift_service_name: YourService
  thrift_service_address: 127.0.0.1:50052

urlmapping:
  - GET,POST /hello SayHello
  - GET /eat_apple/{num:[0-9]+} EatApple
  - GET /a/a EatApple
  - POST /a/a SayHello
  - GET /a/b EatApple
  - GET /a/c EatApple